Added tile system and test level.
UbiBelETF/dagger pull request #127
Opened 2020-12-04 19:13 UTC by Nikolar97

Added a tile system and a test level for it.

2020-12-04 19:32 UTC, UbiBelETF requested changes

2020-12-04 19:32 UTC, UbiBelETF commented on source/dagger/gameplay/team_game/hero_character.cpp
> +hero_character::hero_character()
This...
a) isn't needed because the class doesn't exist
b) doesn't compile because of the class not existing

2020-12-04 19:32 UTC, UbiBelETF commented on source/dagger/gameplay/team_game/tilemap_legends.cpp
> +}
There are many problems here but I want team members to review. Do not merge this as-is.

2020-12-05 12:15 UTC, Becaan approved these changes

2020-12-13 13:53 UTC, merged