Added power up feature. Players speed up and flicker after defending
UbiBelETF/dagger pull request #38
Opened 2020-11-11 23:29 UTC by senadkurtisi

Flickering is just an indicator for the player/s that their power-up is still active.

2020-11-12 07:19 UTC, DPrivalov requested changes
Good job! 

One important thing to change and it's good to merge!

2020-11-12 07:19 UTC, DPrivalov commented on source/dagger/gameplay/ping_pong/power_up.h
> +struct PowerUp
place it inside ping_pong namespace as any other pingpong system

2020-11-12 11:32 UTC, DPrivalov approved these changes

2020-11-12 14:18 UTC, UrosBorovcanin reviewed
The code functions as it should and functions well. The only negative side that i see here is that it doesn't conform to the styleguide.md

2020-11-12 19:39 UTC, DPrivalov approved these changes

2020-11-13 02:00 UTC, UrosBorovcanin approved these changes
The code is up to the style guide standard and still works completely fine.

2020-11-13 12:32 UTC, DPrivalov commented
@Djafex, waiting for u =)

2020-11-13 22:21 UTC, FedjaVujicic approved these changes

2020-11-13 22:28 UTC, merged