Hero movement with animations
UbiBelETF/dagger pull request #97
Opened 2020-11-29 11:41 UTC by Becaan

2020-11-29 14:37 UTC, DPrivalov requested changes

2020-11-29 14:37 UTC, DPrivalov commented on source/dagger/gameplay/team_game/character_controller.cpp
> +    Engine::Registry().view<ControllerMapping>().each([&](ControllerMapping& ctrl_)
we have a better way to get an input, check out other team's requests or simply go to platformer example.

2020-11-29 14:37 UTC, DPrivalov commented on source/dagger/gameplay/team_game/character_controller.cpp
> +            //AnimatorPlay(animator_, "souls_like_knight_character:IDLE");
why is it commented out?

2020-11-29 17:50 UTC, UbiBelETF commented on source/dagger/gameplay/team_game/character_controller.cpp
> +                transform_.position.x += ctrl_.input.x * char_.speed * sqrt(2) / 2 * Engine::DeltaTime();
Is multiplying with `sqrt(2) / 2` supposed to be vector normalization?

2020-11-30 21:09 UTC, DPrivalov approved these changes

2020-12-04 16:49 UTC, merged